added partials to the bot client
Ynng/Highschool-Discord pull request #12
Opened 2020-09-30 20:34 UTC by has12zen

2020-09-30 20:48 UTC, Weezity approved these changes

2020-09-30 20:54 UTC, Weezity commented
I mean idk why use partials if he's already got the commands all set up but I guess it doesn't matter

2020-09-30 23:46 UTC, Ynng requested changes
https://discordjs.guide/additional-info/changes-in-v12.html#clientoptions-disableeveryone

clientOptions.disableEveryone was removed in Discord.js v12

2020-10-01 02:26 UTC, has12zen commented
should I remove it completely?

2020-10-01 02:46 UTC, Ynng approved these changes

2020-10-01 02:47 UTC, merged